#!/bin/bash

echo "🤖 Setting up Real AI for Stylisti..."
echo ""
echo "You need an OpenAI API key to use the real AI assistant."
echo "Here's how to get one:"
echo ""
echo "1. Go to https://platform.openai.com/api-keys"
echo "2. Sign in or create an OpenAI account"
echo "3. Click 'Create new secret key'"
echo "4. Copy your API key (starts with 'sk-')"
echo ""
echo "Then run this command with your API key:"
echo ""
echo "export OPENAI_API_KEY='your-api-key-here'"
echo "npm run web"
echo ""
echo "Or create a .env file:"
echo "echo 'OPENAI_API_KEY=your-api-key-here' > .env"
echo ""
echo "💡 Note: This will cost around $0.01-0.05 per conversation with image analysis"
echo "✨ But you'll get a REAL AI that can actually see and understand your outfits!"